export const SYNONYMS: Record<string, string[] | undefined> = {
	check: ["verify", "verifies", "assert", "ensure", "expect", "validate", "confirm", "see"],
	verify: ["check", "verifies", "assert", "ensure", "expect", "validate", "confirm"],
	verifies: ["check", "verify", "assert", "ensure", "expect", "validate", "confirm"],
	see: ["view", "displayed", "visible", "shown", "find", "check"],
	shown: ["see", "view", "displayed", "visible"],
	visible: ["see", "view", "displayed", "shown"],
	click: ["tap", "press", "select", "choose", "open"],
	clicks: ["tap", "press", "select", "choose", "open"],
	press: ["click", "tap", "select", "choose"],
	navigate: ["go", "visit", "open", "access"],
	navigates: ["go", "visit", "open", "access"],
	go: ["navigate", "visit", "open", "access"],
	open: ["navigate", "navigates", "click", "access", "go"],
	enter: ["type", "input", "fill", "write"],
	type: ["enter", "input", "fill", "write"],
	page: ["screen", "portal", "dashboard", "view", "site"],
	screen: ["page", "portal", "dashboard", "view"],
	portal: ["page", "screen", "dashboard", "site"],
	contract: ["risk", "policy", "slip", "agreement", "endorsement", "declaration", "facility"],
	risk: ["contract", "policy", "slip", "negotiation", "peril"],
	policy: ["contract", "risk"],
	openmarket: ["om"],
	facility: ["fac"],
	endorsement: ["default endorsement", "mtpc", "mtpc endorsement"],
	declaration: ["dec"],
	broker: ["placing", "brokerName0", "brokerName1", "brokerName2", "brokerName3"],
	carrier: ["insurer", "reinsurer", "underwriter", "carrierName0", "carrierName1", "carrierName2", "carrierName3", "carrierName4", "carrierName5", "carrierName6", "carrierName7", "carrierName8", "carrierName9"],
	insurer: ["carrier", "underwriter"],
	reinsurer: ["carrier", "underwriter"],
	underwriter: ["carrier", "insurer"],
	leader: ["lead"],
	lead: ["leader"],
	admin: ["administrator", "config", "administration"],
	administrator: ["admin"],
	administration: ["admin"],
	FO: ["firm order"],
	signed: ["bound", "completed", "finalised"],
	bound: ["bound", "completed", "finalised"],
	BQ: ["bindable", "quote", "bindable quote"],
	write: ["stamp", "authorise", "commit", "line"],
	stamp: ["write", "line", "authorise"],
	sign: ["bind", "complete"],
	bind: ["sign", "complete"],
	digitise: ["create", "upload", "import"],
	inbox: ["dashboard", "home"],
	dashboard: ["inbox", "home"],
	overview: ["summary", "risk overview"],
	summary: ["overview"],
	message: ["text", "content", "label", "notification"],
	text: ["message", "content", "label"],
	history: ["audit", "log", "trail", "timeline"],
	audit: ["history", "log", "trail"],
	log: ["history", "audit", "trail"],
	trail: ["history", "audit", "log"],
	must: ["can", "does", "should", "will", "shall", "verify", "check", "ensure", "has", "possesses"],
	can: ["must", "does", "should", "will", "shall", "able", "has"],
	does: ["must", "can", "should", "will", "perform", "has"],
	should: ["must", "can", "does", "will", "shall", "verify", "check", "has"],
	will: ["must", "can", "does", "should", "shall", "has"],
	has: ["must", "can", "does", "should", "will", "contains", "includes", "with", "possesses"],
	contains: ["has", "includes", "with"],
	permission: ["access", "capability", "right", "role"],
	access: ["permission", "capability", "right"],
	cannot: ["must not", "does not", "will not", "should not", "unable", "does not have"],
	"does not have": ["cannot", "must not", "will not", "should not", "unable"],
	not: ["no", "never"],
	set: ["use", "uses", "change", "update"],
	uses: ["set", "use", "change", "update", "create", "creates"],
	use: ["set", "uses", "change", "update", "create", "creates"],
	status: ["state", "stage", "phase"],
	create: ["use", "uses", "set"],
	creates: ["uses", "use", "set"],
	a: ["an"],
	an: ["a"],
};
