import fs from "fs";
import path from "path";
import type { CatalogData } from "../types";

/** In-memory cache so the catalog JSON is only read from disk once per server lifetime. */
let cachedCatalog: CatalogData | null = null;

/**
 * Loads the Steppy BDD catalog from disk and caches it in memory.
 *
 * The catalog is a pre-built JSON snapshot of all step definitions and scenarios,
 * generated by running `steppy build` against the automation test repository.
 * In production it is injected by the Jenkins pipeline before the Next.js build;
 * in local development it lives at `steppy-web/src/data/steppy_catalog.json`.
 *
 * Subsequent calls return the cached instance — no additional disk I/O occurs.
 *
 * @returns The full CatalogData object containing steps, scenarios, and meta stats.
 * @throws If the catalog file does not exist at the expected path.
 */
export function loadCatalog(): CatalogData {
	if (cachedCatalog) return cachedCatalog;
	const filePath = path.join(process.cwd(), "src/data/steppy_catalog.json");
	cachedCatalog = JSON.parse(fs.readFileSync(filePath, "utf-8"));
	return cachedCatalog!;
}
